### ISSUE TITLE
Changing to red team in any way crashes the game

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#1]
By trying to change to the red team in any way the game crashes, whether it's by the jointeam command, the changeto command or the toggleclasspanel UI.

To reproduce: Switch to red team in any way mentioned above and watch your game crash :p

**Comment by Melectrome** [comment]
UPDATE: This applies to every team (including spectator), and it only crashes during combat phase.

**Comment by TheZoc** [comment]
Fixed on SF 1.9.6 Beta 2
