### ISSUE TITLE
Minimum combat phase time

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#100]
The minimum combat time is 120, trying to set it lower results in a combat time of 2 min. It should be allowed to be set to any positive time (useful for debugging)

**Comment by Melectrome** [comment]
I agree :)
Minimum should be like 5 secs.

**Comment by arenaceous** [comment]
minimum should be 1, or at leads give a warning when set too low

**Comment by Melectrome** [comment]
Same with the build times tbh.

**Comment by Melectrome** [comment]
Also we've hit a milestone 🎉
Issue #100 🎉🎉

**Comment by TheZoc** [comment]
Won't `togglephase` be enough for testing?

I'm not sure I understand what's needed here.

**Comment by Melectrome** [comment]
Just reduce the minimum phase times

**Comment by TheZoc** [comment]
I won't add a warning - too much work, sorry!
(I'd need to learn how that works on source sdk again, sorry!)

Currently, the minimum amount of time is 120 secs.
Are you sure?

There's `addtime` and `togglephase` commands to aid already.

(I'm wondering, why is this needed too :) )

**Comment by arenaceous** [comment]
Yea, min time may as well be 1 second, just makes testing that much easier. plus makes building cubemaps a bit faster. (cubemaps i build during the combat phase)

**Comment by TheZoc** [comment]
@arenaceous You can use `togglephase` to switch phases 😮

**Comment by arenaceous** [comment]
I do, but removing the minimum means I don't have to 👍

**Comment by TheZoc** [comment]
Changed in RC6:
- Removed the hard-coded restriction of phase lengths being 120 seconds minimum.
- Added a warning if the phase length variable is set to anything below 120 seconds.
