### ISSUE TITLE
Retarded but working fix to save sprays

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#104]
So we all know that sprays are borked because they save to config.cfg, but they are for some goddamn reason not loaded and cl_logofile resets to default on gamestartup despite it being declared in config.cfg.
I was testing around and found a really dumb but working way to patch it: Exec it again on startup!

To apply fix: replace the current valve.rc in /cfg/ with the one provided:
[valverc.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2834331/valverc.zip)

I only added a single line to execute config.cfg again. You can see for yourself.

**Comment by TheZoc** [comment]
Nice finding!

Added to RC5 :D
