### ISSUE TITLE
Updated gameserverconfig.vdf

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#105]
I updated the gameserverconfig.vdf file to be on par with the listenserver settings file.
Pls replace for the next RC.
[gameserverconfig.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2871990/gameserverconfig.zip)

**Comment by TheZoc** [comment]
Awesome! Merged for RC5!
Thanks!
