### ISSUE TITLE
Small updates for advanced crosshair support and more

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#108]
A zip containing some updated/new files with the following changes:
- OptionsSubMultiplayer.res adjusted for advcrosshair and advanced options support (see discord for preview)
- Imported TF2/DOD:S simple crosshairs
- HL2/SF1941 crosshair imported as a .vtf to be selectable from the crosshair picker
- Added a sourceforts crosshair background (see discord for preview, multiplayer options image without missing texture)
- Updated settings_default.scr to be more localised
- Added basic advanced settings in user_default.scr

@TheZoc 
[smallstuff.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2921270/smallstuff.zip)

**Comment by TheZoc** [comment]
Added to RC7 😁
