### ISSUE TITLE
Smooth particles fix is broken?

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#109]
https://cdn.discordapp.com/attachments/504401652221214741/550404771685859340/unknown.png
https://cdn.discordapp.com/attachments/504401652221214741/550403836339290112/unknown.png
https://cdn.discordapp.com/attachments/504401652221214741/550403500920537099/unknown.png
and a few more examples (discord)

**Comment by TheZoc** [comment]
Reverted the changes on RC6
