### ISSUE TITLE
Players invincible

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#11]
You know what I'm talking about.

**Comment by TheZoc** [comment]
This needs more investigation. Specially when and why it happens.

**Comment by TheZoc** [comment]
This is elusive as it gets: I have no idea yet what causes it, why it happens (and, ofc, how to fix).

This definitely needs WAY more testing.

**Comment by Nick12506** [comment]
Yeah, right now people can't die from others.

**Comment by TheZoc** [comment]
It seems to be random, I can't find a reason why it is triggered. I wonder if it can be related to #8 in some way.

**Comment by Nick12506** [comment]
I don't think it's random. Sunseille and I are unable to harm each other.

I'd think so though in that mode I'm able to kill people via explosions and with this I am not able to.

**Comment by TheZoc** [comment]
If you can find a sure way to trigger it (steps to reproduce the bug), would be a good help.
Steps to avoid it are also helpful.

Currently, the reason why this happen is unknown

**Comment by Nick12506** [comment]
I haven't played a game with another person that I've been able to kill.

I'll test tmw, 5am here.

**Comment by TheZoc** [comment]
Fixed in Beta 7
