### ISSUE TITLE
pure_server_full.txt necessary improvements

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#110]
Just a simple improvement to the pure_server_full.txt whitelist file to be not overrestrictive and to allow simple mods like crosshair mods or sound mods.
[criticalwhitelistfix.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2932601/criticalwhitelistfix.zip)

**Comment by TheZoc** [comment]
Added to RC6!
