### ISSUE TITLE
Detail Distance Rest

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#112]
The commands
cl_detailfade "5000"
cl_detaildist "7500"
which were added in RC6
reset to their source defaults (400 and 1200 respectively) every map. I have tried putting the commands in the config and autoexec to no avail. They have to be set every map load or change level.

**Comment by Melectrome** [comment]
It's a code/map specific thing afaik, same happens with the commands r_cheapwaterstart and r_cheapwaterend on most TF2 maps, since they have custom visibility/fog settings...

**Comment by arenaceous** [comment]
ah, that makes sense. I guess I'll set it in the map itself with a client command.
