### ISSUE TITLE
­

### ISSUE THREAD

**Issue by Nick12506** [TheZoc/sourceforts-bug-tracker#13]
![beta](https://user-images.githubusercontent.com/11761833/47070055-77480480-d1be-11e8-8b91-63a200bcc884.png)

**Comment by Melectrome** [comment]
Duplicate of [#10](https://github.com/TheZoc/sourceforts-bug-tracker/issues/5)

**Comment by Melectrome** [comment]
This can be fixed by forcing a random (or the same map) string for the `nextlevel` cvar upon the map being loaded

**Comment by Melectrome** [comment]
Or by just completely ignoring it and adding a mapcycle.txt file to /cfg/ ;p
