### ISSUE TITLE
Sprint issues

### ISSUE THREAD

**Issue by TheZoc** [TheZoc/sourceforts-bug-tracker#15]
Prediction is broken on all betas, up to Beta 3

Hopefully I fixed it in Beta 4, but with this fix I broke how it drains stamina and recharge time. This should be fixed in Beta 5, if everything else is working correctly :)

**Comment by Melectrome** [comment]
Seems to be fixed in Beta4 from what I've tested.
Only thing still buggy is the speed multiplier, the depletion multiplliers work fine.

**Comment by TheZoc** [comment]
@Melectrome Mind doing a complete check again, on beta 5?

Flashlight and underwater breathing might be broken or mess up with sprint, but lets focus on sprint, first :)

**Comment by Nick12506** [comment]
When flashlight is enabled, off by default though you should make it on by default. The flashlight works when aux power is at 0. The flashlight does not drain the battery.

The sprint seems synced to the  bar, with the oxygen meter as well.

You do not die from drowning though the bar shows depletion. So if you're sprinting and go under water it will continuously drain.

**Comment by TheZoc** [comment]
Fixed in Beta 6
