### ISSUE TITLE
Jeeps broken

### ISSUE THREAD

**Issue by Nick12506** [TheZoc/sourceforts-bug-tracker#16]
Attempted to create unknown entity type prop_vehicle_jeep!

Put this at the bottom of the fixing pile.

**Comment by TheZoc** [comment]
I think SF194 removed jeeps for some reason... I need to check the old code.

**Comment by Nick12506** [comment]
Send the code and I'll check it for you! :P

**Comment by TheZoc** [comment]
I'll keep this open to avoid other possible bugs lurking around.

**Comment by Nick12506** [comment]
Oh, I clicked the closed button by mistake. There next to each other :/

**Comment by TheZoc** [comment]
Jeep code is unchanged from Source SDK 2013
