### ISSUE TITLE
The flag icon in the player tab menu changes size

### ISSUE THREAD

**Issue by Nick12506** [TheZoc/sourceforts-bug-tracker#17]
![image](https://user-images.githubusercontent.com/11761833/47344926-98559d00-d677-11e8-9358-7a9ebf2c3296.png)

**Comment by TheZoc** [comment]
I have no idea why VGUI is acting odd :(

**Comment by Nick12506** [comment]
It shrinks as time goes on :/

**Comment by TheZoc** [comment]
Fixed with #23
