### ISSUE TITLE
Team Selection class button hovering

### ISSUE THREAD

**Issue by TheZoc** [TheZoc/sourceforts-bug-tracker#18]
Hovering and Clicking a button in the class menu doesn't change it's appearance, even if they're working correctly when clicked.

**Comment by Nick12506** [comment]
Confirming :P

**Comment by Melectrome** [comment]
nofix

**Comment by TheZoc** [comment]
Apparently, this isn't trivial to fix and it's a cosmetic bug, so, I'm closing this one 😞
