### ISSUE TITLE
sf_charger_health_increment has no effect

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#2]
`sf_charger_health_increment` is supposed to increase the amount of health you get from the health chargers. By increasing it, healing doesn't speed up...

To reproduce: Change the `sf_charger_health_increment` cvar server-side to anything above 1, hurt yourself in-game, and use the charger. You'll notice that the health charger still heals like sf_charger_health_increment is set to 1.
Another thing I noticed with this cvar is that unlike `sf_charger_armor_increment`, when you change it you don't get the "Server cvar X changed to 'Y' " chat message.

**Comment by TheZoc** [comment]
Fixed in 1.9.6 Beta 2
