### ISSUE TITLE
Remaining issues in b9

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#20]
## Code related:
- [x] https://github.com/TheZoc/sourceforts-bug-tracker/issues/17
- [x] https://github.com/TheZoc/sourceforts-bug-tracker/issues/18 (there is no indication that button is pressed in the class/team pick menu) Marked as finished, but it's not, since sadly it's a nofix.
- [x] Server console prints `User Msg 'Battery': 2 bytes written, expected 3` with every armor heal when healing from the armor dispenser
- [x] `ERROR: Weapon (weapon_357) using undefined primary ammo type (357)` in server console on launch/map change (doesn't seem to alter gameplay or change anything in any way... Can be ignored for now.)
- [x] There is no "Armor" on the HUD in b9, and the killfeed doesn't show as well. But the armor healing and damage taking seems to be still working, only the counter seems to be hidden.
- [x] B9 linux server won't launch unless you make a copy of all SDK 2013 binaries that end with `_srv.so` and rename them to not have the `_srv` suffix (kinda fixed, we'll just warn server operators)

## Mod-files related (scripts, etc.):
- [x] Multiplayer tab in options is broken - I'm working on it FIXED! I'll post a fix over here in a sec!!!
- [x] "Create server" shows HL2DM server settings in the second tab, but that's an easy fix
- [x] With high ping, switching to the stun batton plays the sound multiple times instead of once. (ommited)
- [x] With high ping, when moving the camera around the weapon doesn't move in the viewmodel, it just stutters and glitches around but stays still (ommited)
- [x] Linux builds has missing textures due to VTF files name cases (script found proved to be working)

That's all the bugs that are left to fix from what I could find. We're so close!

**Comment by markboyall** [comment]
ALso encountered the missing armour on the Windows client.

**Comment by TheZoc** [comment]
@markboyall logs? :)

**Comment by Melectrome** [comment]
When I was playing with `developer 5` I didn't see any errors in console on windows regarding the armor counter missing from the HUD @TheZoc

**Comment by Melectrome** [comment]
Could just be a HUD script error, which sounds like an easy fix, I'm not sure though, since older beta builds had the armor counter showing

**Comment by TheZoc** [comment]
Can you explain (and maybe show a screenshot?) the armor country you're referring to?
I don't remember removing any feature.. Maybe was a regression by mistake?

**Comment by TheZoc** [comment]
Updated first post to be a list :)

**Comment by TheZoc** [comment]
Hopefully Battery error messages are fixed on beta 10

**Comment by TheZoc** [comment]
Added 357 back in. It should *not* be accessible without cheat codes.
I have no idea if it breaks the game or not (try it. Yeah, with cheat codes. If it crashes the game somehow, I"ll remove it again.)

ATT @Nick12506

**Comment by Nick12506** [comment]
Nice addition, also add weapon_citizensuitcase and swap its model with the 1x1x1 for a secret bonus!

**Comment by TheZoc** [comment]
@Melectrome Any updates on the stuff you were working? :)

**Comment by TheZoc** [comment]
List completed! 😁
