### ISSUE TITLE
Minor feature requests :)

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#21]
Some of these sound hard to implement (and most likely are lol), but if everything gets sorted out with the bugs I'd love to see these things added. No forcing though :)
- viewmodel_fov and r_drawviewmodel changeable by client without sv_cheats 1 (making the commands non-cheat)
- Clan tags in scoreboard with cl_clanid
- Option for server operators to force a specific respawn time
- Old SF theme as secondary startup music
- Intro video (old or new whatever) brought back

**Comment by Melectrome** [comment]
.

**Comment by TheZoc** [comment]
If you want me looking into those, I can still look, they're just with a very low priority with this amount of bugs popping up ><
