### ISSUE TITLE
Permanently decreasing sprint bug

### ISSUE THREAD

**Issue by j2k3k** [TheZoc/sourceforts-bug-tracker#24]
Happened twice while bhopping.

First time it lasted until the end of combat, through the build phase, and into the combat phase again until I left the server.

Happened a second time after that while I was only bhopping back and forth.

Appears as though sprint is always decreasing, as if you were holding down the sprint button constantly, and I could not untrigger it.

**Comment by arenaceous** [comment]
I think this was a bug present in 1.9.4x but not very common.

**Comment by j2k3k** [comment]
Possibly, but it happened to me twice within about 30 minutes. I'll try to recreate it when I get a chance here soon

**Comment by TheZoc** [comment]
The sprint system from sf194 was completely replaced in sf196 (with the code being very close to hl2dm)

I wonder if what makes it stuck is the phase toggle at the end of the sprint bar...

**Comment by j2k3k** [comment]
Just to be clear, you think it is holding down sprint and a phase toggle happening at the same time?
If so, I don't think so. Both times it happened to me, it happened during the middle of the build phase.

**Comment by ghost** [comment]
After further testing it doesn't seems to be the togglephase. 
But indeed this bug happend to me too i still don't know what's the deal behind it.

The last time it happend to me was after killing my character by jumping into the void.
I'll do more tests later

**Comment by j2k3k** [comment]
Got it.
It is when you are sprinting, and the sprint bar is decreasing (but not gone) and you die. If you do this it just sticks as permanently decreasing.

**Comment by ghost** [comment]
Confirming the bug append when you die while decreasing the sprint bar.
here's an error.log

[jump_aux.log](https://github.com/TheZoc/sourceforts-bug-tracker/files/2618353/jump_aux.log)

**Comment by TheZoc** [comment]
I changed a lot of sprint code in Beta 12, I'd love if you could report if this was fixed as a side effect :)

**Comment by Sonsari** [comment]
Still happens in Beta 12

**Comment by arenaceous** [comment]
Namely, still decreasing permanently if you die while sprinting.

**Comment by ghost** [comment]
still happens in b12 indeed

**Comment by TheZoc** [comment]
Fixed in Beta 13
