### ISSUE TITLE
SF Logo Art

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#26]
the "²" in the logo was removed for 1.9.3 of SF, however it remains in the art in various places. Is it worth it cleaning up all the art so the ² is removed?

**Comment by TheZoc** [comment]
It would be awesome to remove that.

If someone can do the changes and submit the textures, I'd appreciate :)

**Comment by arenaceous** [comment]
First 2 textures for the flags in Crete. Materials go in materials/banner
[banner.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2614971/banner.zip)

**Comment by arenaceous** [comment]
Delete the current sf194 folder in materials, and replace it with this folder:
[sf194.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2614993/sf194.zip)

**Comment by arenaceous** [comment]
Copy into the decals folder and replace any files.
[decals.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2615018/decals.zip)

**Comment by arenaceous** [comment]
VGUI/endgame replace sf_logo.vtf
[sf_logo.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2615098/sf_logo.zip)

**Comment by arenaceous** [comment]
This fixes some of the odd alpha transparency on the beta logos. Replace files in materials/vgui/sf
[sf.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2618422/sf.zip)

**Comment by arenaceous** [comment]
Replace the entire crate folder in materials with the one below.
[crate.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2618462/crate.zip)

**Comment by TheZoc** [comment]
> Delete the current sf194 folder in materials, and replace it with this folder:
> [sf194.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2614993/sf194.zip)

This one... Images are in a different order.. Also, 1.5x4 looks... odd (non-recognizable, I think?)

I don't recall how this works, but do you think we should have a 1x1x1 image?

**Comment by TheZoc** [comment]
> Delete the current sf194 folder in materials, and replace it with this folder:
> [sf194.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2614993/sf194.zip)

This one confuses me...
Are we using the old texture with the ² on the logo?

**Comment by TheZoc** [comment]
> Replace the entire crate folder in materials with the one below.
> [crate.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2618462/crate.zip)

`crate_tex_final_none.vtf` is missing.
(It has a different hue to it, even being red)

**Comment by TheZoc** [comment]
Applied all changes to Beta 11.

sf194 folder concerns me... The textures are different, and 1.5x4 texture is missing.

@arenaceous Can you check this, please? :)

**Comment by arenaceous** [comment]
I renamed the textures slightly, so it makes more sense, the vtfs have the correct texture for the crate, the vmts point to the correct texture. This is a holdover from the original sf2 crate having textures in a different order.

With the sf194 folder i made a slight mistake, the vmts point to the sf textures (as they were duplicates however i forgot to update the sf textures) please replace the textures in the sf folder with the ones below.
[sf.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2618825/sf.zip)

**Comment by arenaceous** [comment]
I have updated the resource icons for to be the logo @TheZoc provided. These 3 files belong in sourceforts/resource
[resource.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2622076/resource.zip)

**Comment by arenaceous** [comment]
Last one to close this bug is the eDIT block spawner model which I'll complete in the next few days.

**Comment by TheZoc** [comment]
@arenaceous So, you're willing to move the textures from sf194 folder to the sf folder?

They were kept to allow compatibility with 1x1x1 block.

Also, I'm considering (seems to be easy enough) to add 1x1x1 block support via command console
(sf_allow_cube ? name undecided yet)

What do you think about all of this? :)

**Comment by TheZoc** [comment]
About resources:
Quality seems better, right? 😁 
![image](https://user-images.githubusercontent.com/924927/49197991-4d1a6280-f378-11e8-8bdd-3843c12cc2b4.png)

Do you think anything must be changed? :)

Also, about sourceforts_big.tga file, it looks like this:

![image](https://user-images.githubusercontent.com/924927/49198205-30325f00-f379-11e8-93ba-b5b7e7571d00.png)

It seems there are issues with the border... Can those be fixed/improved? :)

**Comment by arenaceous** [comment]
Theres only so much one can do to make a pixel bend into a circle, especially when the picture is 32x32.

**Comment by TheZoc** [comment]
> I renamed the textures slightly, so it makes more sense, the vtfs have the correct texture for the crate, the vmts point to the correct texture. This is a holdover from the original sf2 crate having textures in a different order.
> 
> With the sf194 folder i made a slight mistake, the vmts point to the sf textures (as they were duplicates however i forgot to update the sf textures) please replace the textures in the sf folder with the ones below.
> [sf.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2618825/sf.zip)

This is the only fix I haven't added, to avoid breaking previous maps. I'm considering reverting the changes to those textures, to keep the cube spawners in place (and enabla-able via console variables).

What do you think?

**Comment by arenaceous** [comment]
That's fair enough, you will also need to modify the VMTs that point to the vtfs.
