### ISSUE TITLE
Menu Background

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#27]
The Menu background says 1.9.4 on it.
In addition, when in widescreen, the background art is stretched.
Ideally, if there is source for the background art, 3 VTFs can be produced, for 4x3 16x9 and 16x10, and then these used when the game in the relevant aspect ratio.

**Comment by TheZoc** [comment]
The background probably would need a new texture. The previous one is nowhere to be found (while not stretched, I really like it).

If no one can create an adequate texture, I"m included to use the 1.9.6 that @melectrome created

**Comment by Nick12506** [comment]
Can we get a copy of that up of Melectromes uploaded to here?

**Comment by arenaceous** [comment]
Melectromes background:
[background01.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2614865/background01.zip)

**Comment by Melectrome** [comment]
https://fdl.melectro.me/sourceforts/background01.tga :p

**Comment by arenaceous** [comment]
I've updated this, but will include it in a larger texture fix. I removed the version number and included a cropped widescreen version.

**Comment by TheZoc** [comment]
@arenaceous send file? :)

**Comment by TheZoc** [comment]
Added the new, versionless background, provided in another issue (can't find the exact number now)
