### ISSUE TITLE
FGD updates

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#28]
I've updated the FGD for 1.9.6 few minor changes:
infodecal gets a model rather than a hideous box that blocks the entire view of said decal.
env_block_spawner is updated to be correct with regards to the blocks it spawns
ammocrates health and suit chargers can now be parented.
Icon for game_phase_control
Icon for env_block spawner
@TheZoc Note: use the FGD attached here its more up to date than the one I sent you.
This FGD is backwards compatible with 1.9.4
[sourceforts.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2614055/sourceforts.zip)

**Comment by TheZoc** [comment]
Updated `sourceforts.fgd` to latest source sdk 2013.

Please, test it! (File attached, if everything is okay, will be included in beta 11)


[sourceforts-fgd.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2614200/sourceforts-fgd.zip)

**Comment by Nick12506** [comment]
Did you patch the original FGD or the community patched copy from 1.9.4.1? @arenaceous

**Comment by TheZoc** [comment]
Was there a community fixed one? Upload here please...

Both uploaded here were based on original sf194 one

**Comment by TheZoc** [comment]
If a community fixed one shows up, please, reopen this :)

**Comment by arenaceous** [comment]
Minor change to make the func_disposer_selective easier to use.

[sourceforts.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2628680/sourceforts.zip)

**Comment by arenaceous** [comment]
@TheZoc  Adding Item_healtkits and batteries to the FGD as they were missing. [sourceforts.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2652379/sourceforts.zip)

**Comment by TheZoc** [comment]
Added to Beta 13
