### ISSUE TITLE
Missing Pictures/Icons

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#29]
Not sure how to add these by default, but we are missing the grid view and list view pictures in steam. Additionally, the icon visible in the list view is only the small icon, there is no large version of the icon.

**Comment by TheZoc** [comment]
I'm confused.. Can you give more details about this?

**Comment by ghost** [comment]
- Everything seems good there
![steam_sf_list](https://user-images.githubusercontent.com/45349537/48996893-195bf480-f14e-11e8-800b-f1e01991b0e9.png)


- no big icons
![steam_sf_biglist](https://user-images.githubusercontent.com/45349537/48996899-224cc600-f14e-11e8-8b4a-2c57ae059167.png)


- no large icon
![steam_sf_grid](https://user-images.githubusercontent.com/45349537/48996904-24168980-f14e-11e8-9385-9b4cc430efbe.png)

**Comment by arenaceous** [comment]
In the first image, the sorceforts logo is only 16x16, it should be 32x32. Missing in the resource folder is a 32x32 sourceforts_big.tga Do we have an icon source?

**Comment by TheZoc** [comment]
I managed to find an old logo file, and I messed with its colors to try and mimic SF194 icon.
Here is the result, probably far from perfect, but it's close. Gradient colors might be off, but should be simple to adjust.

Do you think you you can create these? (Need someone more talented/trained with art than me for this task)

I can also share the file I found, but it's in a crappy state... Still, if you want it, tell me.

SVG file on the zip, PNG file attached for easy previewing

[sf196logo.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2618665/sf196logo.zip)


![sf196logo](https://user-images.githubusercontent.com/924927/49064007-87f98a80-f200-11e8-800e-1ac80893ebcd.png)

**Comment by TheZoc** [comment]
Added in beta 11

**Comment by Melectrome** [comment]
Bump, what about the banner stuff mentioned in @Sunseille's comment? I couldn't find the files for that in other games, but there must be a way to set them, right?

**Comment by TheZoc** [comment]
I haven't found a way :(

**Comment by phit** [comment]
the images are hosted on Steam servers, if you manually wanna set them they are placed in `Steam\userdata\[yourid3]\config\Grid\`
so there is no proper way to ship them with the installation

e.g. http://cdn.akamai.steamstatic.com/steam/apps/220/header.jpg

**Comment by arenaceous** [comment]
you could put the image in every folder that is in userdata.
