### ISSUE TITLE
Missing detail.vbsp and lights.rad

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#30]
As the title says. These generate sprites for blend maps and lights for textures. They sit in the root of the sourceforts mod folder.

[sourceforts.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2614836/sourceforts.zip)

**Comment by TheZoc** [comment]
Added to Beta 11.

@arenaceous, these files seem to have more stuff in them than the ones I could find in valve vpk's. Do they include fixes, anything I should know about?

**Comment by arenaceous** [comment]
A few extra things for some textures in the 195/6 Valley, which I havent yet finished off.

**Comment by TheZoc** [comment]
Okay, I added those files, let me know if I need to update them :)

**Comment by arenaceous** [comment]
I've updated the lights.rad file for a few upcoming textures, and also included them here.
[lights.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2635611/lights.zip)
