### ISSUE TITLE
MOTD Logo

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#31]
The MOTD displays the hl2 logo, rather than a SF one. Also some shenanigans in the right hand corner.
![image](https://user-images.githubusercontent.com/11131401/49009501-9aaa9a00-f1d5-11e8-887e-7e5baf4ac351.png)

**Comment by TheZoc** [comment]
Maybe the logo in #29 can be updated to replace that one?

**Comment by Nick12506** [comment]
Small chance that texture is a custom font..

**Comment by Melectrome** [comment]
The logo from #29 will definitely do more than well. Thanks for posting it. Alternatively we could use the image that Sourceforts facebook uses

**Comment by TheZoc** [comment]
The image on #29 uses a gradient. I was wondering if one half-red and half-blue would be more appropriate for a while, now..

**Comment by TheZoc** [comment]
Fixed it on beta 14!

![image](https://user-images.githubusercontent.com/924927/49683289-417e1880-faa9-11e8-82b8-75a9f5565a21.png)

Sadly, the square on the top/right corner doesn't seem to be fixable. It it a symbol font ("r" letter, on the font Marlett, included in the source sdk 2013), but I couldn't find a way to display it ☹️
