### ISSUE TITLE
beta screenshots shared into a folder

### ISSUE THREAD

**Issue by ghost** [TheZoc/sourceforts-bug-tracker#33]
**`Informations`**
As the title say you can find screenshots made by @TheZoc in sourceforts/screenshots
It's great to get beta screens available, but that's 1.2MB wasted

**`how to do`**
you can check them by going into sourceforts/screenshots

**`screenshots/videos`**
well, there are 3 screenshots indeed

**`version`**
beta 10

**`OS`**
Windows - Linux

**Comment by TheZoc** [comment]
Nice Catch @Sunseille! Thank you!

(You might need to keep an eye open for these, since I might add them by accident again... I apologize in advance! 😁 )
