### ISSUE TITLE
Startup video not working

### ISSUE THREAD

**Issue by ghost** [TheZoc/sourceforts-bug-tracker#34]
**`Informations`**
startupvid.avi isn't working at the startup of the game. 

**`how to do`**
start the game
it goes directly to the main menu skipping the video

**`screenshots/videos`**
"startupvid.avi" in sourceforts/media

**`version`**
beta 10 and less

**`OS`**
Windows - Linux

**Comment by j2k3k** [comment]
Per Sunseille's request-

I've been beta testing since 1.9.3 and no one has noticed or at least made it known until now I believe. Meaning, no one has cared since 1.9.2 . Personal opinion also, loading videos are annoying.

The time being used to fix this could be used to fix something else.

**Comment by arenaceous** [comment]
That also is what -novid is for

**Comment by TheZoc** [comment]
If you know how to fix it, I can add a fix for the sake of completeness...
I have searched for a solution for this for a while, but eventually gave up :(

**Comment by Melectrome** [comment]
The video was updated from the combine soldier to a new animation and it hasn't been playing for a long time afaik. It could have to do something with the codec of the video. There's a command that can play videos to test if they're readable by source. I'll look into this.

**Comment by Melectrome** [comment]
Converted the video to Bink which most source engine games use.
I recommend to also change the name of StartupVids.txt to be lowercase like I did in the zip, just in case linux fails on reading it or sth :p
Oh, and since we now have a better and working .bik version, we should remove the .avi
[media.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2659944/media.zip)

**Comment by Melectrome** [comment]
As it turns out, due to licensing issues, we cannot use a startup video for legal reasons, unless we pay an insane price for such a small thing... Bullshit if you ask me, but whatever. This issue needs to be closed sadly.

**Comment by Melectrome** [comment]
Turns out I'm retarded. We can use Bink.
