### ISSUE TITLE
Linux missing textures

### ISSUE THREAD

**Issue by ghost** [TheZoc/sourceforts-bug-tracker#35]
**`Informations`**
Linux build can't read textures ; materials ; models instead the source engine map the level with purple/black and ERROR where it's needed.

**`how to do`**
play some maps on linux build
exemples:
1. purple/black textures = sf_sphinx
2. ERROR model = block spawner in sf_tactical

**`screenshots/videos`**
1. purple/black:
![bp_texturescsf19beta](https://user-images.githubusercontent.com/45349537/49066636-13cfde80-f222-11e8-964a-40ca9c8cbc9d.png)

2. ERROR model:
![error_model_sf19beta](https://user-images.githubusercontent.com/45349537/49066657-21856400-f222-11e8-9181-0d2a2d496314.png)

**`version`**
beta 10

**`OS`**
Linux

**Comment by ghost** [comment]
can be fixed with a bash script put into the sourcemods folder:
```BASH
#!/bin/bash
for SRC in `find sourceforts/{models,materials} -depth`
do
    DST=`dirname "${SRC}"`/`basename "${SRC}" | tr '[A-Z]' '[a-z]'`
    echo "${SRC}"
    if [ "${SRC}" != "${DST}" ]
    then
        [ ! -e "${DST}" ] && mv -T "${SRC}" "${DST}" || echo "${SRC} was not renamed"
    fi
done
echo "done!"
```

fixed everything for me
[linux_materials_fix.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2618891/linux_materials_fix.zip)

**Comment by Nick12506** [comment]
Can you see if sf_tread works for you? Those models are paked inside it's map.

**Comment by ghost** [comment]
sf_tread doesn't work on linux
textures and models are missing

**Comment by TheZoc** [comment]
Reopening, since this is something that still needs to be done :)

**Comment by arenaceous** [comment]
Please run this on the folder I provided you, and then when b12 is released, I can work on the textures again.

**Comment by ghost** [comment]
seems ok on the b12

**Comment by TheZoc** [comment]
I'll run this later on - for now, I want to avoid introducing any new hard-to-track bug
(We never know, right? ☹️ )

**Comment by TheZoc** [comment]
Added this to beta 14.

**Comment by TheZoc** [comment]
@Sunseille I worry that the content in vmt files still points to upper case files, wonder if this would break the mod in later builds of the sdk (if they ever get updated).

Would it be a good idea to write a script to fix those aswell?
