### ISSUE TITLE
weapon_cubemap missing

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#36]
Tested in both buildphase and combat phase
`sv_cheats 1; impuse 81; give weapon_cubemap`
This debug weapon is useful for mappers in testing cubemaps.

**Comment by TheZoc** [comment]
I just tried here, and got this:

![image](https://user-images.githubusercontent.com/924927/49199067-3c202000-f37d-11e8-86e1-c193e449d0ba.png)


It seems to be working...

```
sv_cheats 1;
impulse 81
```

got this on console
```
] sv_cheats 1
] impulse 81
Late precache of models/shadertest/envballs.mdl -- not necessarily a bug now that we allow ~everything to be dynamically loaded.
Loading: models/shadertest/envballs.mdl
Loading models/shadertest/envballs.mdl
Late precache of models/shadertest/envballs.mdl, need to rebuild modelsounds.cache
(22.98) output: (trigger_multiple,) -> (blue_spawndoor,Disable)()
(22.98) input : blue_spawndoor.Disable()
(23.26) output: (trigger_multiple,) -> (blue_spawndoor,Enable)()
(23.26) input : blue_spawndoor.Enable()
```

**Comment by arenaceous** [comment]
I still couldnt get this to work without changing the bucket position to 1 in the weapon_cubemap.txt script
