### ISSUE TITLE
buildcubemaps crashes the game

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#37]
Can't build cubemaps in game, or at least it crashes when it has finished building [cubemaps](https://developer.valvesoftware.com/wiki/Cubemaps).

**Comment by arenaceous** [comment]
[Possible workaround](https://github.com/ValveSoftware/source-sdk-2013/issues/403)?

**Comment by TheZoc** [comment]
Related links:
https://github.com/ValveSoftware/source-sdk-2013/issues/40 - cubemaps not working
https://github.com/ValveSoftware/source-sdk-2013/issues/403 - [HLDMS] Default env_cubemaps

On Valve wiki ( https://developer.valvesoftware.com/wiki/Cubemaps ), we have this comment:

> Note:	If the map bsp file is renamed after the cubemaps have been built the cubemaps will no longer work and default to the sky cubemap. You must rebuild cubemaps again each time a map is renamed. However, the no-longer-working cubemaps are not removed, so this can lead to bloated files. If you plan to release a map so that others can download it, it is best to try to avoid any map-renaming after you compile it, to avoid problems.

This might help while the map is being created, as a workaround.

**Comment by TheZoc** [comment]
I removed `Cubemap_CreateDefaultCubemaps()` function call from VBSP. Please, let me know if this works :)

[SourceSDK2013-bin-VBSP-fix-01.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2627601/SourceSDK2013-bin-VBSP-fix-01.zip)

If everything works, it might be easy to add a line parameter for this 😉

**Comment by TheZoc** [comment]
This is a Source SDK 2013 issue, I can't fix it.
Using less than 50 env_cubemap entities seems to be the way to go (testing required).

Also, the attached VBSP might help with building cubemaps without the need to mess with [VIDE](https://developer.valvesoftware.com/wiki/VIDE) utility.
