### ISSUE TITLE
$Detail

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#38]
So with the update to orange box, all custom textures should really use [$detail](https://developer.valvesoftware.com/wiki/$detail). SF textures in game next to stock textures look a bit flat without $detail. Basically the parameters need to be added to every vmt on a per material basis.

**Comment by TheZoc** [comment]
I don't see anything enforcing that, on the link, but apparently it won't be as easy as creating a script to add a "sane" value to them.

You'd need to carefully inspect and add those as necessary (is it? won't it change the overall look/feel of the game?)

It seems a lot of work to be done tbh!

**Comment by arenaceous** [comment]
There's nothing enforcing it, that's true, it just looks a little better. I've started working on it either way.

**Comment by TheZoc** [comment]
Merged all the submitted changes, with exception of Greenhorntrim 24 and 25.

**Comment by arenaceous** [comment]
Please stick with the current b11/b12 textures for greenhorntrim 24 and 25.

**Comment by TheZoc** [comment]
Done! Closing this for now :)
