### ISSUE TITLE
SLAMs

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#39]
When you change class, any SLAMs you have deployed stay deployed.

**Comment by TheZoc** [comment]
If we ignore them what happens?

**Comment by arenaceous** [comment]
Well I died when I ran into them.

**Comment by arenaceous** [comment]
I think ignoring is technically a valid strategy, and this is a non-bug. Just in other games (like tf2) any deployables are removed when you change class.

**Comment by TheZoc** [comment]
Fixed this behavior in Beta 12 - Needs testing.
