### ISSUE TITLE
Freezing shotgun animations

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#4]
**This issue is a placeholder, it needs to be investigated more.**
When two or more shells are fired from the shotgun, when reloading the animation shows the first shell being loaded, and then the animation freezes. It comes back when the shotgun is fully reloaded, then the reload animation stops and the shotgun is back to normal.

To reproduce: Fire two or more shells from the shotgun, and watch the animation.

**Comment by TheZoc** [comment]
Fixed in 1.9.6 Beta 2, by removing Tony Sergi animation fixes
