### ISSUE TITLE
Death sounds when changing team

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#40]
When changing team, you die, but you play the death sound of the team you changed to.

**Comment by TheZoc** [comment]
What about the player model?
Is it consistent with the death sound?

**Comment by arenaceous** [comment]
The player model is of the team you were on (so correct), the death sound is the team you changed to (incorrect).

**Comment by TheZoc** [comment]
With further inspection (using `thirdperson` cheat), apparently, you change model and play enemy team sound when changing teams (and dying, in the process).

This also seem to be the same behavior of HL2DM, I just tried it.

Would it be okay to keep as is?
(It might be a lot of headache to change this behavior)

**Comment by arenaceous** [comment]
Yea, pretty minor bug

**Comment by TheZoc** [comment]
Closing it :)
