### ISSUE TITLE
Missing decals in sf_crete

### ISSUE THREAD

**Issue by L1pE** [TheZoc/sourceforts-bug-tracker#41]
Or at least that's what I can only imagine is causing this:
![sfdecal1](https://user-images.githubusercontent.com/11803296/49200649-d899f080-f384-11e8-917c-93431b026838.png)
![sfdecal2](https://user-images.githubusercontent.com/11803296/49200651-d899f080-f384-11e8-8f31-4476378a82d4.png)
![sfdecal3](https://user-images.githubusercontent.com/11803296/49200652-d899f080-f384-11e8-943b-a2996f1de9f1.png)

I noticed these console messages when loading the map:
```
material "sf/decals/sf_attach_plate" not found.
env_cubemap used on world geometry without rebuilding map. . ignoring: sf/decals/sf_decaltitle
material "decals/graffiti_blue_team" not found.
material "decals/graffiti_red_team" not found.
```
There is no "sf_attach_plate" inside "materials/sf/decals", and no "decals" folder at all directly inside "materials" folder as the "graffiti" errors suggest. There is a VMT for "graffiti_blue_team" in "materials/vgui/logos".

Game version: 1.9.6 beta 10
OS: Linux (doubt that matters in this case)

**Comment by TheZoc** [comment]
@arenaceous :)

**Comment by arenaceous** [comment]
Map in progress.

**Comment by ghost** [comment]
do the same on linux

**Comment by arenaceous** [comment]
This should be closed as it is fixed in the b17 release of maps.
