### ISSUE TITLE
Startup Image

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#42]
When starting up SF, it shows a hl2dm picture, not a SF picture. Could just show the menu background while loading.

**Comment by TheZoc** [comment]
I don't think this is fixable :(

**Comment by Melectrome** [comment]
Fixable, I was about to point it out.
For whatever reason, SourceForts has the loading picture for HL2DM included, which is a VERY easy change since its just a picture lel. I'll paste a full path to that image soon, I'm on my phone atm.

**Comment by TheZoc** [comment]
@Melectrome Updates on this? 😃

**Comment by TheZoc** [comment]
Fixed on b13 :)
