### ISSUE TITLE
Missing sounds in dedicated server

### ISSUE THREAD

**Issue by Denis101** [TheZoc/sourceforts-bug-tracker#43]
No sounds play when grabbing the flag or scoring when playing in a dedicated server.

**Comment by ghost** [comment]
From what we tried yesterday it was on a ubuntu server `linux`, i'll give it a shot when i can
- linux
- beta10
- any maps

**Comment by Melectrome** [comment]
Could have something to do with the capital letter stuff.

**Comment by Melectrome** [comment]
Or now that I think of it, Source engine games have files defining sounds to be played in specific events. I'll look into it.

**Comment by TheZoc** [comment]
@Sunseille @Melectrome @Denis101 

Can you inspect the file `scripts/game_sounds.txt` and see if everything is correct, for linux?
Or even if the file is found by linux? (well... you know the drill...)

In code, we have:
```cpp
#define FLAG_RED_TAKEN "CTF.RedTaken"

// ...

PrecacheScriptSound(FLAG_RED_TAKEN);

// ...

PlayFlagSound(FLAG_RED_TAKEN);
```
(On different areas of the code, ofc)

**Comment by TheZoc** [comment]
Can we get a few systematic tests in these?

- Listen server (host test)
- Listen server (connected client test)
- Dedicated server (connected client test)

Both for windows and linux in each case?

This way it will be easier to isolate the issues.

Sounds to try:
- Flag touch sound
- Flag capture sound
- Match winning sound
(I'm not sure if it's a good idea to test for each team, but it's good to report what you did in any case 😉 )

**Comment by Melectrome** [comment]
I tested this with @TheZoc on b13, we were both windows, server was linux.
All sounds played perfectly fine...

**Comment by TheZoc** [comment]
@Sunseille @Denis101 Can you guys try this?

And, please, try out of the "docker" servers too, just in case something is wrong in there :)

(@Melectrome server seems to be working fine, would be nice to try in there)

**Comment by TheZoc** [comment]
No more complaints, I'll close this issue. 
It seems to be fixed.
