### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#44]
Name now uses Steam name, you cant make a local in game name.

**Comment by Denis101** [comment]
think this is a feature of source sdk 2013. Have you tried changing your name on steam instead?

**Comment by arenaceous** [comment]
Thats fine, then name as a command shouldn't exist.

**Comment by Nick12506** [comment]
If we can bring it back, custom names per server are better imo..

**Comment by Melectrome** [comment]
Imo it's better to have the same name in-game and in steam. It gets confusing when people use different names for everything.

**Comment by TheZoc** [comment]
This is how source sdk 2013 behaves.

RIP Cactus Fantástico

**Comment by arenaceous** [comment]
Zoc the issue here then is the name command should be removed

**Comment by TheZoc** [comment]
I did a through search for the `name` console variable, and it's defined in a portion of the code that isn't accessible (i.e. not in the public SDK code). Can't change this behavior 😞
