### ISSUE TITLE
General Physics object freezing

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#46]
It seems you cant freeze general physics objects, like func_physbox. This used to be the case. It just says you cant freeze that here.

**Comment by Nick12506** [comment]
I'd need to make a test map to confirm though wasn't that a glitch originally?

I was able to freeze unfreezable objects by placing them in a nofreeze zone then removing them from such zone in 1941. 

It would be great to be able to initially freeze object without needing for them to enter a nofreeze trigger though.

**Comment by arenaceous** [comment]
sf_sandbox has physics objects. They can freeze in 1941 but not 196.

**Comment by TheZoc** [comment]
IIRC, the freezing code exists for prop_physics objects.
I don't recall anything about func_physbox (didn't remember it existing up to now).

What behavior do we actually want?

**Comment by arenaceous** [comment]
Freezing as per standard blocks for both of the physics objects

**Comment by TheZoc** [comment]
Uhh, I feel silly, but mind rephrasing that?
(Seems ambiguous to me, but it's probably just the foreign language barrier)

**Comment by arenaceous** [comment]
Make freezing of physics blocks (like prop_physics and func_physbox) behave like standard block freezing in game.

**Comment by TheZoc** [comment]
Oh man, this area of the code is a mess... Could be HARD to fix that without rewriting a lot of stuff (which I hope I can avoid).

Some interesting bits:

- Every `CPhysicsPropBlock` starts with `SetFreezeable(true)`
- `func_nofreeze` and `func_flagzone` only toggles `prop_block` and `prop_physics` freeze flag (in a poor, hacky way).
- They do not check if the entities are actually blocks in there, even though `IsBlock()` function exists for every `CPhysicsProp`, but is only true on `CPhysicsPropBlock` (HACKFEST!)
- `CPhysBox` is a subtype of `CBreakable`, which is a subtype of `CBaseEntity`, not a real physics prop (`CPhysicsProp`)
- `IsFreezeable()` and `SetFreezeable()` exists for every `CBaseEntity`

If the hackish way to check for Freezeable entities on `func_nofreeze` and `func_flagzone` are odd enough, they might be able to change the Freezeable state of the `CPhysBox`'es

(Yup, it's Freezeable not Freezable, in the code 😉 )

A big rewrite would be required for this. Tell me how much important this kind of stuff is, please :)

**Comment by TheZoc** [comment]
I added the ability to freeze `func_physbox` in beta 14 without needing to rely on `func_nofreeze`.

Not sure if this is ideal, but shouldn't break anything on the regular maps :)
