### ISSUE TITLE
Flag follows player view

### ISSUE THREAD

**Issue by j2k3k** [TheZoc/sourceforts-bug-tracker#47]
https://vimeo.com/303856454 pw is 196

Took a video because it was too weird to explain. Basically (after dying I believe?), the flag will stay in the players peripheral and will not go away.

This also results in the flag model not being at the spawn. So for example in the video you see the red flag in my corner view. When I went to the red flag area after the flag had 'returned', there was no flag there. I walked over where  the flag was and suddenly I had it again, then I dropped it, the flag disappeared out of my screen.

It happened twice today while playing.

**Comment by Nick12506** [comment]
That video is private.

**Comment by j2k3k** [comment]
The pw is 196

**Comment by TheZoc** [comment]
Is this a local problem only (i.e. other players can see the flag in the correct position), or the flag position is indeed wrong server-wide?

**Comment by j2k3k** [comment]
Local only

**Comment by TheZoc** [comment]
Do you think you can find the exact steps to replicate it? ><
I couldn't get it to happen on my side yet...

**Comment by j2k3k** [comment]
Sorry, I've been super busy. Next time we play I'll try to get it nailed down

**Comment by TheZoc** [comment]
Updates? :)

**Comment by TheZoc** [comment]
Hopefully this isn't a big issue, really just a cosmetic one...
I can't find a way to reproduce it, so I'm closing it for now.
