### ISSUE TITLE
1.9.6 Feature Request Thread

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#48]
I had a few new ideas since I made my old "minor feature requests" issue, and from what I can read in the discord, you guys have a few suggestions too. So I decided to make this thread/issue where we can post suggestions and feature requests for 1.9.6. I'll start.
**DISCLAIMER**: Obviously, these are just requests/suggestions. I don't WANT them to be added otherwise I'll die, I'm just saying that it'd be cool to see this stuff added.
- viewmodel_fov and r_drawviewmodel changeable by client without sv_cheats 1 (making the commands non-cheat)
- Clan tags in scoreboard with cl_clanid
- Option for server operators to force a specific respawn time
- CVAR to change teammate/global player collisions

Implemented:
- ~~Freezestatus as an in-game feature~~
- ~~Old SF theme as secondary startup music~~
- ~~Intro video (old or new whatever) brought back~~ Confirmed impossible due to licensing issues with Bink video tools.
- ~~More "Create Server" options in the GUI (e.g. Blocklimit, Flashlight, Force Respawning)~~
- ~~Have things packed in VPK's so that we can implement `sv_pure` for servers ( #65 )~~

**Comment by Melectrome** [comment]
And yes, I do realise some of these are marked as issues already, namely no intro video and others

**Comment by arenaceous** [comment]
Not to make more work, but freezestatus integrated into the game.

**Comment by TheZoc** [comment]
What is "freezestatus"?

**Comment by arenaceous** [comment]
Freezestatus is/was a plugin that when activated via the console/keybinding would tell anyone (not just admins) who last froze and unfroze the block you are looking at, their name, steam id, and IP address.

**Comment by j2k3k** [comment]
Freezestatus should 100% be implemented int 196 and into all new versions of SourceForts.

I also do not believe it should be tied to bans. There used to be servers with that functionality and it almost always resulted in wrongful bans

**Comment by TheZoc** [comment]
Do you have the source code of that plugin?
(The plugin itself would be helpful, but I doubt it would be compatible at all)

**Comment by arenaceous** [comment]
https://forums.alliedmods.net/showthread.php?t=64131
It looks like the .sp file is source.

**Comment by Melectrome** [comment]
Updated the issue with some more suggestions :p

**Comment by TheZoc** [comment]
Added freeze status
Should behave differently from the linked plugin, need tests :)

**Comment by TheZoc** [comment]
I don't think this is viable for a mod, is it?
`Have things packed in VPK's so that we can implement sv_pure for servers`

**Comment by TheZoc** [comment]
I have no idea what this means:
`CVAR to change teammate/global player collisions`

**Comment by TheZoc** [comment]
Regarding this:
`More "Create Server" options in the GUI (e.g. Blocklimit, Flashlight, Force Respawning)`

Please, edit `cfg/settings_default.scr` (with a text editor) to add the features.
All the possible variables are in `VARIABLES.txt` file (which is markdown file, you can rename it to .md if you have a markdown editor, for better viewing)

Also, please note that some variables are obscure (and there's some I couldn't even understand exactly what they do, and there was no comment or explanation in the code), so, just add what's useful there.

Last but not least... Keep "fun" variables out of the server customize dialog :)

**Comment by TheZoc** [comment]
`Clan tags in scoreboard with cl_clanid` I wish to add this, probably won't have time...

**Comment by Melectrome** [comment]
> `Clan tags in scoreboard with cl_clanid` I wish to add this, probably won't have time...

Yeah, the cl_clanid stuff was far fetched and it was kind of a last minute idea I got from playing Counter-Strike too much.
Would be nice to see it though, especially since SourceForts was all about clans back in the day, but I know that implementing this would take a long time and might even conflict with the current scoreboard layout...
> Regarding this:
> `More "Create Server" options in the GUI (e.g. Blocklimit, Flashlight, Force Respawning)`
> 
> Please, edit `cfg/settings_default.scr` (with a text editor) to add the features.
> All the possible variables are in `VARIABLES.txt` file (which is markdown file, you can rename it to .md if you have a markdown editor, for better viewing)
> 
> Also, please note that some variables are obscure (and there's some I couldn't even understand exactly what they do, and there was no comment or explanation in the code), so, just add what's useful there.
> 
> Last but not least... Keep "fun" variables out of the server customize dialog :)

Will do the create server stuff on monday :)

> I have no idea what this means:
> `CVAR to change teammate/global player collisions`

By default there are player collisions enabled (meaning you cannot walk into and through your teammates etc). It's okay, but in big casual games this can become troublesome. This is why adding a cvar to disable these player collisions would be awesome, since you wouldn't constantly bump into people.

> I don't think this is viable for a mod, is it?
> `Have things packed in VPK's so that we can implement sv_pure for servers`

Okay, I'll admit, it is a bit of a hassle (although if you know how to do it and you have an RSA key it's pretty quick and easy), but sv_pure is a simple way to prevent easy hax just by slightly altering the mod files. With some VMF edits, you can see people through walls, hear things you wouldn't probably hear in big fights etc.
Take a look at this for example:
https://web.archive.org/web/20170812222225/http://gamebanana.com:80/gamefiles/3827
While some of the stuff there got patched, most of the stuff still works on servers without sv_pure.
Overall, while lack of sv_pure does prevent customization on some servers, it may give an unfair advantage over other players for some in competitive matches.

**Comment by TheZoc** [comment]
More info regarding pure servers
https://developer.valvesoftware.com/wiki/Pure_Servers

And how to create VPKs
https://developer.valvesoftware.com/wiki/VPK

This would be the very last addition to the mod, if it will happen.

**Comment by TheZoc** [comment]
Moved this to #65 

`Have things packed in VPK's so that we can implement sv_pure for servers`

**Comment by TheZoc** [comment]
I think the rest of the requests in this issue aren't easy to implement without a major change in the code...
I guess we got a good amount of them in :)
