### ISSUE TITLE
Incorrect move speed when respawning after death

### ISSUE THREAD

**Issue by L1pE** [TheZoc/sourceforts-bug-tracker#49]
During the combat phase, when you respawn after death, your normal movement speed will be set to 190 HU/s regardless of class. Sprinting once fixes it and sets the correct move speed for the class until next respawn. Changes nothing for Rocketeer whose move speed is already 190 by default.

Version 1.9.6 Beta 11

**Comment by TheZoc** [comment]
This required more changes than I expected to fix - which might impact other parts of the sprint and movement speed systems.
Tests are required!

Hopefully fixed on beta 12, without adding new bugs in its place 😁

**Comment by L1pE** [comment]
On beta 12, now the issue is that every class during the combat phase will always move at Scout speed.

**Comment by L1pE** [comment]
Issue persists in yet another form on beta 13. On the first spawn after the build phase ends, you will be set to 190 HU/s move speed regardless of class, respawning after death sets the correct move speed, but only up until the first time you sprint, after which your move speed will be set to 190 HU/s until death.

**Comment by TheZoc** [comment]
This one is a dodgy one!

Can you give the exact steps to reproduce reproduce the current behavior? I'm having trouble to reproduce it locally :(

Please, try it on the beta 14 and let me know :)

**Comment by L1pE** [comment]
I create a listen server (possibly different behavior on dedicated? Hadn't considered that), have cl_showpos 1 set, and then just put a high host_timescale value until build phase ends (I don't know a better way to skip it), then put it to 1 again, move around and check the speed values, kill myself with a grenade or some other explosive, respawn and move some more. I'd test after multiple game restarts and the behavior would be the same. So far I tested only on Linux, but this is the kind of thing I'd imagine would be the same on Windows. I can give it a try on Windows too though and see what happens.

**Comment by L1pE** [comment]
Well, tested now on beta 14 on both Windows and Linux, turns out it really is a Linux-only issue, speeds are set properly on Windows. On beta 14 in Linux the behavior is the same as beta 13.

**Comment by TheZoc** [comment]
Fixed on beta 15!
