### ISSUE TITLE
Bugs after match end

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#5]
**This needs a little bit more of investigation**
After a match ends, the map changes very quickly, and everything seems to be normal until you spawn. The timer is at 0, the scores in the scoreboard are the same, and the image in the scoreboard saying which team won is still there. Additionally, when you shoot you fire extremely fast and you don't loose bullets.

To reproduce: Finish a match (either by slow and painful waiting or by a few `addtime -999` commands), and wait for the map to change. You'll see the results upon respawning.

Some notes: This has only been tested on a local listenserver with only one map in the mapcycle, so this really needs some investigation. The super short map change time is also suspicious.
Oh, and doing the `changelevel` command changes the level and fixes this bug... Still, this shouldn't be normal.

**Comment by Melectrome** [comment]
Small update: When the mapchange is supposed to occur the console says that the server can't change to the next map (in 1.9.6 Beta 1 case it's sf_skywalk). **This needs more investigation!**

**Comment by TheZoc** [comment]
Can you try adding another map from SF19.4 and modifying `maplist.txt` in the mod directory to see if this is fixed, please? :)

**Comment by Melectrome** [comment]
Will do.

**Comment by Melectrome** [comment]
I fixed it by adding a mapcycle.txt file into the /cfg/ folder. This needs to be documented in server tutorials. SF1.9.4.1 had a similar issue of missing mapcycle.txt in /cfg/.

**Comment by Nick12506** [comment]
Thanks, we'll just need to make sure to include one on the release.

**Comment by TheZoc** [comment]
So, We just need to move the file to the cfg folder and that's it?

**Comment by Melectrome** [comment]
Fron what I've tested, yes. The mapcycle.txt file is supposed to be in the /cfg/ folder in sdk 2013 just like in tf2 from what it seems.

**Comment by TheZoc** [comment]
I moved `mapcycle.txt` to /cfg/, will be in the correct folder in Beta 5 (Sorry, just missed it for beta 4)

Any idea about the supposed location for the file `maplist.txt`?

**Comment by Nick12506** [comment]
I think the Maplist.txt has always been in the root of sf dir. I pulled up multiple SF backups I have and they've all been there.

**Comment by Melectrome** [comment]
Ugh, this needs to be open for a while longer, I'm getting headaches. This needs way more investigation

**Comment by Nick12506** [comment]
With the map archive placed into the map folder this doesn't happen anymore..

**Comment by TheZoc** [comment]
It was tough tracking that down, but @Nick12506 helped me to test that.

How bad would it be to keep it as a *known issue* and warn server admins to keep a well written mapcycle.cfg?

**Comment by TheZoc** [comment]
This will remain as a known issue: If there's a map in the list that isn't present in the folder, the server will freak out / present this bug.

As long as the map list (inside `mapcycle.txt`) is correct, everything works fine.
