### ISSUE TITLE
Scrolljump not working

### ISSUE THREAD

**Issue by ghost** [TheZoc/sourceforts-bug-tracker#53]
**`Informations`**
You can't scrolljump on the new source SDK
It's quite primordial since it's used by everyone as higher level

**`how to do`**
bind jump to your mousewheel, then scroll your mousewheel once you take a ramp and you should be able to jump higher

**`version`**
beta 12

**`OS`**
Windows ; Linux

**Comment by TheZoc** [comment]
Unless someone can find a patch to apply to the code that re-enables it, we won't have this bug/feature in the game :(

I don't know how it worked in the previous SDK and, sadly, we don't even know if this is in an area of the code that's accessible to us.

On the other hand, if someone finds a fix to re-enable this, please, reopen this issue 😁

**Comment by Melectrome** [comment]
It's intended. Scrolljumps were patched in newer sdk's. It was a physics and prediction bug in old source engine versions.
