### ISSUE TITLE
Pistol animations broken

### ISSUE THREAD

**Issue by damienn** [TheZoc/sourceforts-bug-tracker#55]
From first person, single pistol shots have a 'hiccup,' reload animation does not play.  Looks fine from 3rd person/watching someone else.

**Comment by damienn** [comment]
Upon further testing, this did not happen on my own listen server, but did occur on Acer's

**Comment by j2k3k** [comment]
https://vimeo.com/305615892
Video. Pw - 196

**Comment by damienn** [comment]
Here is a clip of the serverlog

SourceForts V1.9.6 Beta
Map: sf_skywalk
Players: 2 / 12
Build: 4630212
Server Number: 87

Error loading cfg/trusted_keys_base.txt
The server is using sv_pure 0.  (Enforcing consistency for select files only)
Voice_Init: Using Steam voice optimal sample rate 24000
Press N to select a team / class
You are on team Unassigned - press N to select
Compact freed 425984 bytes
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Redownloading all lightmaps
Auto-selecting a team.
You will respawn as a Engineer.
You are on team Red
Jake^ suicided.
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
Jake^ suicided.
You're not allowed to freeze this object here.
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
You're not allowed to freeze this object here.
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
weapon_physcannon[135]: Playing sequence 4 but there's only 4 in total?
****************************************BUILD PHASE ENDS****
weapon_frag[157]: Playing sequence 6 but there's only 2 in total?
weapon_frag[157]: Playing sequence 6 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 7 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 7 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 9 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 9 but there's only 2 in total?
Jake^ :  fine now
weapon_pistol[156]: Playing sequence 9 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 9 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 7 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 7 but there's only 2 in total?
thirst :  still errors
thirst :  look in console
Jake^ :  oh yeah
Jake^ :  post those too <3
weapon_pistol[156]: Playing sequence 9 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 9 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 9 but there's only 2 in total?
weapon_pistol[156]: Playing sequence 9 but there's only 2 in total?

**Comment by TheZoc** [comment]
Apparently those warnings are from hl2dm

https://steamcommunity.com/groups/WeAreUnitedGamers/discussions/0/846955554775707800/

I'm not sure why they happen. The "fix" in there just filters the messages, it's not a real fix.

**Comment by TheZoc** [comment]
More info on this, apparently happens in every source game, including portal 2:

https://github.com/ValveSoftware/Source-1-Games/issues/1886

**Comment by damienn** [comment]
Weird, maybe the dedicated server that is up is outdated or bugged?  Not sure who's it is

**Comment by TheZoc** [comment]
The animations themselves could be a failure in the prediction, "lag prevention" algorithm.. I think it fails for anything above 100ms

**Comment by Melectrome** [comment]
I was unable to reproduce this bug in Beta 17, Beta 16 or even Beta 15... Anyone else??

**Comment by Melectrome** [comment]
I was able to reproduce this at last.
It only happens when you switch to thirdperson and back to first person, and it's temporary, since when you die everything is back to normal.

**Comment by TheZoc** [comment]
I guess this is not fixable, then...
(Or at least, it isn't worth investigating)

Thanks for finding out the cause! :)
