### ISSUE TITLE
Borderless window mode does not work

### ISSUE THREAD

**Issue by damienn** [TheZoc/sourceforts-bug-tracker#56]
Not visible in display options
Does not work with the launch options -w -noborder

**Comment by TheZoc** [comment]
I don't think this is a feature from SourceSDK 2013. Can you confirm it is?

**Comment by damienn** [comment]
It should be from 2007+  But I cannot seem to find much info on it.  It was an option available since the orangebox update, some other mods had the option when they were still around,  Probably not a huge deal but could be tacked onto the nice-to-have list.

**Comment by Melectrome** [comment]
It's toggled by typing -sw -noborder into launch options. It works for me 🤔

**Comment by damienn** [comment]
hmm i was using -w, ill try -sw next time

**Comment by damienn** [comment]
can confirm -sw -noborder works

**Comment by Melectrome** [comment]
@damienn 
`-w` is the command for window width, just like `-h` is for window height. That explains a lot!
`-sw` means "Start Windowed" I believe.
