### ISSUE TITLE
nades turn purple after another team steals it

### ISSUE THREAD

**Issue by damienn** [TheZoc/sourceforts-bug-tracker#57]
https://media.discordapp.net/attachments/504401652221214741/521851576717934592/sf_skywalk0002.jpg?width=835&height=470

After a nade is picked up by an opposing engineer it no longer swaps colors but merges the two into a rather nice shade of purple, making it impossible to tell if it is friendly or not.

**Comment by Nick12506** [comment]
I like this, I think it's a good feature because nades have friendly fire enabled and as long as everyone can die when it's purple it's okay.

I'd keep it as is imo

**Comment by TheZoc** [comment]
Fixed on Beta 17
