### ISSUE TITLE
(Maybe more than) A few things

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#59]
- [ ] When the auto weapon switch is off, the weapons are not colored to the team's color in the HUD, instead they are defaut yellow.
![image](https://user-images.githubusercontent.com/35193841/49943781-1c463b80-fee9-11e8-8c99-f66f519307e8.png)
- [ ] A few strings are missing from the translation files (For example: "You will respawn as X"), and some strings don't change even if you change them in translation files (e.g. "Object_Frozen" and "Object_Unfrozen")
- [ ] On some maps (like sf_sphinx) you can left click on a block button and it will spawn the block anyways
- [ ] Going up on clipped stairs sometimes makes your camera jitter (most visible on the side stairs on sf_basin)
- [ ] Server console spammed `DataTable warning: player: Out-of-range value (166.109039/100.000000) in SendPro
pFloat 'm_flSuitPower', clamping.
` for unexplained reasons when I was playtesting with wind^
- [ ] Freezestatus is buggy with unfrozen blocks

### Fixeds
- [x] When you change languages, the game prompts you to restart to apply the changes. When you restart, it instead launches SDK 2013 (I feel like this is a nofix, not sure though)
**UPDATE**: Yep nofix
- [x] tiny thing, there's a random image named "normal.tga" in the mod folder of beta 17.
- [x] I can join my Beta 15 (actually beta 16) server when I'm on Beta 16 (actually beta 17). I can play normally, but the versions (and even their gameinfo.txt files) are different and this shouldn't happen.
I checked the hashes of all biniaries in both versions, and they were different.
**SOLUTION**: Change the name of the "Game" in server/client libraries; it's currently set to "SourceForts V1.9.6 Beta".
I don't know if we want to really fix this because some people are against...
**UPDATE**: Supposedly changed in Beta 18.
- [x] ~~Secondly:
_srv suffixes in linux binary files. Are they necessary? They are just copies of normal binaries but with a _srv suffix. I know that this kind of thing is necessary for SDK 2013 binaries, but is it necessary for mod binariers???~~
**UPDATE**: Turns out they are necessary. Server won't start without them. Wouldn't symlinks be easier though and more space-efficient?
**UPDATE2**: Compiler thing.
- [x] The `sf_charger_health_increment` cvar is still broken and doesn't change the speed of health chargers... Additionally, changing it doesn't announce anything in chat unlike `sf_charger_armor_increment`.
- [x] There are no thirdperson shotgun reloading animations **NOFIX**
- [x] (This was present in 1.9.4.1 as well) switching weapons midair makes you tposed until you land **NOFIX**

**Comment by Nick12506** [comment]
At least we can have a everyone play a different beta match :/

**Comment by TheZoc** [comment]
```
On some maps (like sf_sphinx) you can left click on a block button and it will spawn the block anyways
```

ATT @arenaceous

**Comment by TheZoc** [comment]
```
A few strings are missing from the translation files (For example: "You will respawn as X"), and some strings don't change even if you change them in translation files (e.g. "Object_Frozen" and "Object_Unfrozen")
```

I couldn't find a single example of string localization on server side. I'm not willing to experiment with this for the amount of time that will take (we gotta release!). If you have a working solution, let me know and I'll add it.

**Comment by TheZoc** [comment]
Having all of these in a single topic is hard for me to track ><

Anyway, please, move "Freezestatus is buggy with unfrozen blocks" to a different issue and detail it, with images if possible :)

**Comment by TheZoc** [comment]
``Server console spammed DataTable warning: player: Out-of-range value (166.109039/100.000000) in SendPro pFloat 'm_flSuitPower', clamping.``

This was not supposed to happen at all o.O
This piece of code prevents it from going above 100.0:

```cpp
//-----------------------------------------------------------------------------
// Purpose: Interface to add power to the suit's power supply
// Input:	Amount of charge to add
//-----------------------------------------------------------------------------
void CHL2_Player::SuitPower_Charge( float flPower )
{
	m_HL2Local.m_flSuitPower += flPower;

	if( m_HL2Local.m_flSuitPower > 100.0 )
	{
		// Full charge, clamp.
		m_HL2Local.m_flSuitPower = 100.0;
	}
}
```

Do you mind trying to find out what exactly triggers this?
Is it at all related with the flashlight? (I mean, if this issues pops before flashlight, don't try to mess with it before we tackle this isolated issue, first!)

**Comment by TheZoc** [comment]
```
There are no thirdperson shotgun reloading animations
  (This was present in 1.9.4.1 as well) switching weapons midair makes you tposed until you land
```

Can't do much there :/

**Comment by TheZoc** [comment]
And, please... Split the issues! It's horrid to track them like this :(

**Comment by Melectrome** [comment]
Will do, but on monday, since I'm ultra busy today.

**Comment by Melectrome** [comment]
Split all issues.
