### ISSUE TITLE
Team change bug(s)

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#6]
**This one needs slightly more investigation as well.**
During build phase, when you change teams you get teleported to spawn but you don't get suicided.

To reproduce: The server has to be in build phase. Use the `jointeam` command or the class change UI to change teams, and experience the weirdest bug ever.

**Comment by TheZoc** [comment]
Fixing this was non-trivial.

I added a hack to allow players to take damage of the type DMG_GENERIC during build phase.
I think there isn't another source of this kind of damage during build phase, so I think we'll be fine here.
