### ISSUE TITLE
Healing allies with grav gun

### ISSUE THREAD

**Issue by Sonsari** [TheZoc/sourceforts-bug-tracker#61]
In 1941 and previous versions you could hold left click on allies with the gravity gun to restore hp/shield.

**Comment by TheZoc** [comment]
Is this supposed to happen, or was it a weird/bug feature?

**Comment by Sonsari** [comment]
It was a feature of the game, just doesn't work in 196, sorry should have specified

**Comment by Melectrome** [comment]
Can confirm, it was a feature
_and was used hella lot when health chargers were broke_

**Comment by TheZoc** [comment]
Added this bug as a feature to Beta 20
