### ISSUE TITLE
Rejoining team after spectator

### ISSUE THREAD

**Issue by Sonsari** [TheZoc/sourceforts-bug-tracker#62]
You don't spawn after rejoining a team after spectating.
-Join a team
-Join spectator
-Join a team

**Comment by Melectrome** [comment]
Maybe a bit more elaborate:
- Join a team and spawn
- Without doing anything else, open the classteam menu and change to spec
- Try to join back to any team.
After that you are only able to respawn if the phase changes

**Comment by Melectrome** [comment]
_
] developer 5
Counting player="huck dunt" m_iClass=2, m_iNewClass=2, team=2
About to check class limits.
fMaxClassPercentage=75.000000,fCurClassPercentage=0.000000
iClassMembers=1, team->GetNumPlayers()=0, (team != GetTeam())=1
Entering: void CHL2MP_Player::SetPlayerTeamModel( void )
Here: e:\development\github\sourceforts\mp\src\game\server\hl2mp\hl2mp_player.cpp 640
Leaving: void CHL2MP_Player::SetPlayerTeamModel( void )
Entering:CBaseEntity* CHL2MP_Player::EntSelectSpawnPoint( void )
Couldn't find free team spawn point
Leaving:CBaseEntity* CHL2MP_Player::EntSelectSpawnPoint( void )
You will respawn as a Engineer.
You are on team Spectator
Counting player="huck dunt" m_iClass=2, m_iNewClass=2, team=1
About to check class limits.
fMaxClassPercentage=75.000000,fCurClassPercentage=0.000000
iClassMembers=1, team->GetNumPlayers()=0, (team != GetTeam())=1
Entering: void CHL2MP_Player::SetPlayerTeamModel( void )
Here: e:\development\github\sourceforts\mp\src\game\server\hl2mp\hl2mp_player.cpp 640
Here: e:\development\github\sourceforts\mp\src\game\server\hl2mp\hl2mp_player.cpp 653
Leaving: void CHL2MP_Player::SetPlayerTeamModel( void )
You will respawn as a Engineer.
You are on team Red
_

Console output with `developer 5` when attempting to recreate

**Comment by TheZoc** [comment]
Fixed on Beta 20
