### ISSUE TITLE
SLAM fuckery

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#63]
You can still attatch slams to players
You can attatch slams to slams being held by a player
you can attatch slams to unfrozen blocks which makes the block immovable (it can freeze mid air until the slam explodes)

**Comment by TheZoc** [comment]
Oh boy...

So, I need you guys to choose between the current behavior and previous behavior.

Previous seems better imo, but I'd like to hear your opinion.

**Comment by arenaceous** [comment]
If you attach slams to people or the slams they are holding do they explode rather than float? If so then I think this is better behavior.

**Comment by arenaceous** [comment]
![image](https://user-images.githubusercontent.com/11131401/50029273-1cfce000-0057-11e9-8155-5dbf5fec4899.png)
Slam laser got orphaned when it blew up.
how I triggered it was to put a laser slam on a laser slam on an unfrozen block and then moved the block.

**Comment by arenaceous** [comment]
if you place a slam on a slam the second laser is not pointed the right way.
![sf_astrodome0000](https://user-images.githubusercontent.com/11131401/50029789-dad49e00-0058-11e9-9e33-ab10a3f892b9.jpg)
the slam which i am currently in the beam of, is actually triggered to the left of my position (normal to the laser face of the slam as you would expect)

**Comment by Melectrome** [comment]
The old behaviour is better imo. It's closer to the HL2DM behavior, it's more consistent and less buggy.
I think it's best if we bring back the old SLAM behavior.

**Comment by TheZoc** [comment]
It's possible to keep destructive SLAMs and just change the attaching code, if we roll back.

One of the issues with the new code is that it changes the collision code from VPHYSICS to BBOX, that's probably what causes a few os these issues, but it isn't easy to change back.

**Comment by Melectrome** [comment]
Pls lets roll back to the old behavior then, I don't mind flying SLAMS since its the only real issue with the old behavior.

**Comment by TheZoc** [comment]
@Melectrome What do you think about shooting the slams?

I can revert the SLAM patch, but keep them "damageable", so people can destroy them by shooting

**Comment by TheZoc** [comment]
- Reverted SLAM attaching behavior
- SLAMs can still be killed by enemies

Added to Beta 20
