### ISSUE TITLE
(Misc) Translation file stuff

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#67]
A few strings are missing from the translation files (For example: "You will respawn as X"), and some strings don't change even if you change them in translation files (e.g. "Object_Frozen" and "Object_Unfrozen")

**Comment by TheZoc** [comment]
Not happening, sadly.
All the server printed stuff can't be translated easily.

(If someone knows a way, tell me and I'll surely add it in :) )

**Comment by Melectrome** [comment]
Rip. Maybe 1.9.6.1. Closing.
