### ISSUE TITLE
Camera jitter on stairs

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#69]
Going up on clipped stairs sometimes makes your camera jitter (most visible on the side stairs on sf_basin)

**Comment by TheZoc** [comment]
Clipped, you mean, those with the "no clip" areas?

**Comment by arenaceous** [comment]
Clipped with playerclip so the stairs should act as a ramp and not jitter.

**Comment by Melectrome** [comment]
^
Thing is, it's smooth, but your camera kind of flies around.
Oh, and when I turned off cl_predict it stopped.
So it could most likely be a prediction issue....

**Comment by arenaceous** [comment]
Just to confirm its a prediction issue. I've replaced the ramps with stairs so its a little bit less jittery but not much.

**Comment by TheZoc** [comment]
Closing this, in favor of #51.
I think the best possible fix was added already :)
