### ISSUE TITLE
Crouch stuttering

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#7]
**This one also needs more research, because it has only been tested on a local listenserver.**
Any movement while crouched appears to be stuttery.

To reproduce: Crouch and move around. Notice how the camera instead of moving smoothly stutters. This is most visible when bunnyhopping after sprinting.

**Comment by TheZoc** [comment]
Seems to be working fine here. Mind testing again in Beta 2? :)

**Comment by Melectrome** [comment]
Will do

**Comment by Melectrome** [comment]
[https://youtu.be/Wl_QRjax8kE](https://youtu.be/Wl_QRjax8kE)
I made a video example. It's still noticeable on the default `cl_interp` setting (0.1), it's more noticeable the lower your `cl_interp` is.
If it's not really noticeable in the video, try it for yourself in-game.

**Comment by Melectrome** [comment]
This is confirmed to be only a problem in singleplayer listenservers. HL2DM and sourceforts 1.9.4.1 have the same issue. Closing!
