### ISSUE TITLE
Freezestatus wonky with unfrozen blocks

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#71]
Freezestatus is a bit weird with unfrozen blocks.
Everything works fine, but:
When you unfreeze a block, and an enemy picks it up to change the color to theirs you will still see the freezestatus unless you move away a bit and come back or you turn away and turn back to the block.

**Comment by TheZoc** [comment]
So, you will keep seeing its status, until you lose the block as a target and re-target it?

Seems acceptable enough for me.. Any reason that's important to change this behavior?

**Comment by TheZoc** [comment]
No more complaints or feedback, I"m closing this issue.
