### ISSUE TITLE
Custom folder and readme.txt

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#73]
Since we're using sv_pure now and mods need to be in the /custom/ folder in the mod dir, we have to add the folder in installers and add a readme.txt similar to tf2's readme.txt (linked below) explaining the new mod system.

[tf2's readme.txt from /tf/custom](https://github.com/TheZoc/sourceforts-bug-tracker/files/2696804/readme.txt)

**Comment by Nick12506** [comment]
Here's a version modified to fit SF.

[ReadMe.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2696900/ReadMe.txt)


Add modifications and upload if you see something wrong with this adaptation to SF.

**Comment by TheZoc** [comment]
I can't understand if sv_pure is even working right now. Test and report, please.

Also, do gameinfo.txt need any change?

**Comment by TheZoc** [comment]
Added folder and instructions to the next release
