### ISSUE TITLE
Missing line of code in gameinfo.txt relating to /custom/

### ISSUE THREAD

**Issue by Nick12506** [TheZoc/sourceforts-bug-tracker#74]
I couldn't get hammer to recongize my custom models/materials in hammer and with discord saw that 

Line 57* of GameInfo should be

            game+mod            |gameinfo_path|custom/* 

Example below in gameinfo.txt of how it is in mine that caused the /custom/ to be picked up by hammer.

			game+mod			|gameinfo_path|vpk/sfclassic_materials.vpk
			game+mod			|gameinfo_path|vpk/sfclassic_models.vpk
			game+mod			|gameinfo_path|vpk/sfclassic_sound.vpk

			game+mod			|gameinfo_path|custom/*

			game+mod			hl2mp/custom/*
			game+mod			hl2/custom/*

**Comment by TheZoc** [comment]
Are the game assets done in the "first found, first serve" order?

if so, would this make sense?

```
		game+mod			|gameinfo_path|custom/*
		game+mod			hl2mp/custom/*
		game+mod			hl2/custom/*

		game+mod			|gameinfo_path|vpk/sfclassic_materials.vpk
		game+mod			|gameinfo_path|vpk/sfclassic_models.vpk
		game+mod			|gameinfo_path|vpk/sfclassic_sound.vpk
```

**Comment by TheZoc** [comment]
I think #73 is related to this

**Comment by Nick12506** [comment]
I have not thought of this. I'll verify tonight.

**Comment by Nick12506** [comment]
Yes, your edit fixed this issue. 
 
Keep #73 open, I'm unsure of that one right now.
