### ISSUE TITLE
Dropping flag off the edge reset

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#79]
If I recall correctly, there was a timer added in 193 so when the flag was dropped off the edge it took a while to return to the team it was taken from (to prevent stealing the flag and dropping it off the edge to get flag touches). In sfc RC1 the flag instantly respawns when dropped off the edge, however it takes some time for the flag returned announcement to play. I suggest re-instating the flag timer and synchronizing the audio to when the flag respawns.

**Comment by TheZoc** [comment]
Okay, this is what causes this behavior:

- When the flag is dropped, it sets a timer (actually, a "SetNextThink"), with the delay of `sf_flag_pickupdelay`, to return the flag.
- When the flag is dropped into a `func_disposer`, it is instantly returned (checked sf193 code, works the same way)
- While already on the base, the previously set timer triggers, playing the return sound, etc.

**Comment by TheZoc** [comment]
I just added an (ugly) hack to prevent the silent return + loud return later on.

I'm a bit ashamed to write such poor code, but, damn, SF code quality is hard to work with already ☹️
