### ISSUE TITLE
More console spam

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#80]
`weapon_shotgun[112]: Playing sequence 7 but there's only 4 in total?`
Is printed whenever another player shoots the shotgun.
This also happens with other weapons.

**Comment by TheZoc** [comment]
This was already reported in #55 

It's a HL2DM bug.

https://steamcommunity.com/groups/WeAreUnitedGamers/discussions/0/846955554775707800/

I feel bad about adding this "fix" for this, but I guess there's no way out of it.
I'll add to the next build.
