### ISSUE TITLE
Pure server whitelist improvements

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#82]
`pure_server_whitelist.txt` has some issues.

First of all, there was no need to type out every single file into this text file, as you can just use the following syntax:
`sound\...                            trusted_source`
`models\...                           trusted_source`
`materials\...                        trusted_source`
`particles\...                        trusted_source`
to target files recursively [as mentioned in the valve wiki](https://developer.valvesoftware.com/wiki/Pure_Servers) and the TF2 pure server whitelist example (about that later)

Secondly, `pure_server_whitelist.txt` is a filename reserverd for whitelist rules set by the server operator. The mod should only provide the files: `pure_server_minimal.txt` and `pure_server_full.txt`, where minimal should have only critical file enforcements (like block models to avoid wallhacks, player models etc.) and full should have full file consistency (like in the code snippet above).

And lastly... This is more of a request, can we include `pure_server_whitelist_example.txt` like TF2 does to inform server operators on setting up these whitelists? And can we add comments to full and minimal to not edit them and to look in the example file? Linking all three whitelist files from TF2 as examples.
[pure_server_minimal.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2706066/pure_server_minimal.txt)
[pure_server_whitelist_example.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2706067/pure_server_whitelist_example.txt)
[pure_server_full.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2706068/pure_server_full.txt)

**Comment by TheZoc** [comment]
@Melectrome Can you, please, craft the exact file required for us, please, since you seem to have learned a lot about the whole process? :)

**Comment by Melectrome** [comment]
> @Melectrome Can you, please, craft the exact file required for us, please, since you seem to have learned a lot about the whole process? :)

Will do.

**Comment by Melectrome** [comment]
@TheZoc In the next RC, can you include the /scripts/ folder to be VPK'd?

**Comment by Melectrome** [comment]
Other than that, I did it.
Just make sure to VPK /scripts/ for next update pls
[pure_server_whitelist_example.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2707383/pure_server_whitelist_example.txt)
[pure_server_full.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2707384/pure_server_full.txt)
[pure_server_minimal.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2707385/pure_server_minimal.txt)

And just for safety, in the /cfg/ folder, can you make a copy of trusted_keys.txt named trusted_keys_base.txt? Thx <3
Oh and obviously remove the file named pure_server_whitelist.txt

**Comment by Nick12506** [comment]
I don't see why /sound\ should be restricted. I've never met a hacker that hacked with sound and that's the field I've studied for over a decade formally..

**Comment by Melectrome** [comment]
Actually, I kinda agree, but keep in mind that full is for full file consistency - full purity, meaning no mods at all. It's not a default setting as well, so dont worry.

Ultimately everything is up to the server operators, these are just files meant to be as examples/tournament-level enforcements.

PS: What about something that amplifies grenade/sniper shot sounds or block unwelding sounds making them hearable from afar during fights easily?

**Comment by TheZoc** [comment]
Added all those files to RC3, with some modifications (i.e. `trusted_keys_base.txt` was copied from hl2dm, to use valve keys)

I don't get why add scripts to vpk, but I just did it.

While I'll be closing this issue, I'd love if you ( @Melectrome ) could verify if everything is correct on RC3 :)
