### ISSUE TITLE
sv_pure major fix

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#87]
No foreword. Just fix this in next release please. @TheZoc 

Changes needed to be made:
- [x] Update gameinfo.txt with the one attatched to this issue
- [x] Remove trusted_keys.txt
- [x] Replace trusted_keys_base.txt with the one attatched to this issue

Files:
[gameinfo.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2807761/gameinfo.txt)
[trusted_keys_base.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2797632/trusted_keys_base.txt)

**Comment by Melectrome** [comment]
Okay, maybe I do need to give some context.
What this does is delete the unused trusted_keys.txt file, and make it so that trusted_keys_base.txt has both the Valve public key and the sourceforts public key as trusted keys, meaning that sourceforts files and hl2/sdk2013mp files will be trusted on pure servers.

The gameinfo.txt is basically a cleaned-up version that loads only the necessary files in the right way and in the right order.

**Comment by TheZoc** [comment]
Merged for RC4
