### ISSUE TITLE
SF Icon fix

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#88]
Simple fix to make the sourceforts icon appear in the taskbar.
Without this fix:
![image](https://user-images.githubusercontent.com/35193841/51910254-fad4dc80-23ce-11e9-82e1-33c668fd4037.png)

WITH the fix:
![image](https://user-images.githubusercontent.com/35193841/51910222-e55fb280-23ce-11e9-8b82-5c2be8232874.png)

## How to apply the fix
- [x] Change names of the following files:
in /sfclassic/resource:
Change sourceforts.ico to game.ico
Change sourceforts.tga to game.tga
Change sourceforts_big.tga to game_big.tga
From this
![image](https://user-images.githubusercontent.com/35193841/51910425-6fa81680-23cf-11e9-8349-5084e69201a6.png)
To this
![image](https://user-images.githubusercontent.com/35193841/51910381-58692900-23cf-11e9-9492-177b50c2242c.png)

- [x] The change is already applied to the gameinfo fix, so apply this too: https://github.com/TheZoc/sourceforts-bug-tracker/issues/87

**Comment by TheZoc** [comment]
Merged in RC4
