### ISSUE TITLE
Missing steam.inf fix

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#90]
Sourceforts classic has a missing steam.inf file, a file that tells steam which game is being played for counting hours and displaying on the profile.
Without it, a few issues arise like SDK 2013 Multiplayer's hours not being added on your steam profile, game played not being displayed and (rarely) being unable to connect to servers and more.

I made one for SF. To fix simply place in the mod directory (/sfclassic/)
[file.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2808234/file.zip)
(Attatching in a zip because github won't let me upload the raw .inf file)

**Comment by TheZoc** [comment]
Where did you get that info from? 😮 

Added to RC4

**Comment by Melectrome** [comment]
Simply copied the one from SDK 2013 Multiplayer.
Steam uses this file to check what game is being played so that it can count hours.
