### ISSUE TITLE
Version number in bottom-right corner?

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#92]
I'd love to see the return of the version number in the bottom-right corner. And not with the background image this time! It should be a vgui thing. I don't know how hard would it be to add additional text to a main menu @TheZoc

**Comment by TheZoc** [comment]
I don't think this is easily implementable :(

Maybe modify the title2 position for that?
(Change it's version to `Classic 1.0` perhaps?)

**Comment by Nick12506** [comment]
Classic 1.0 RC4*

**Comment by Melectrome** [comment]
I tried doing it. It works!... But only for 16:9.

**Comment by Nick12506** [comment]
If the position is the issue for non 16:9 , move it to the top of the SourceForts logo. So that everyone can see it..

**Comment by Melectrome** [comment]
top of the sourceforts logo?
wdym?

**Comment by TheZoc** [comment]
I think there's a specific prefix for aligning to the right. I"m willing to guess "r100" would work 100 pixels from the right of the screen.

Need to test, though.

**Comment by TheZoc** [comment]
Any updates on this? :)

**Comment by Melectrome** [comment]
r100 doesn't work
its impossible i think
and i dont want to experiment tbh
closing

**Comment by TheZoc** [comment]
I still wanna take a look into this :)
Reopening

**Comment by TheZoc** [comment]
Changed it for RC6, details on #91
