### ISSUE TITLE
Jitter when going up ledges or up clipped stairs is still a thing

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#95]
Is this a nofix? Last issue about this was kind of unclear, so I'm starting a new one.
Basically, if you walk up clipped stairs or ledges (like the side of sf_basin), you get camera jitter.
This is most likely a prediction issue.
Same happens when surfing.

To reproduce: Join a server (you have to have some ping), go up normally or sprint up the side ramp on sf_basin or any map which has somewhat steep ramps and watch your view go slowly into insanity.

**Comment by Melectrome** [comment]
UPDATE: Seems that this is also a HL2DM issue. What the fuck?

**Comment by Melectrome** [comment]
Visuals.
From HL2DM, but the same bug applies to sourceforts.
https://www.youtube.com/watch?v=mkJ_He6kMDs
https://www.youtube.com/watch?v=JbGE0UaCuv4

**Comment by arenaceous** [comment]
This is a no fix as it's an engine prediction issue.

**Comment by TheZoc** [comment]
Yeah, Source Engine issue :(

**Comment by Melectrome** [comment]
Can we reopen this?
