### ISSUE TITLE
Maplist

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#96]
The maplist should be updated so its not alphabetical (so overload and overloaded aren't adjacent) and include the new maps (excluding sandbox).

Possible suggestion attached.

[maplist.txt](https://github.com/TheZoc/sourceforts-bug-tracker/files/2819967/maplist.txt)

**Comment by Melectrome** [comment]
Maplist.txt definitely needs to be updated as new maps are added. And A-Z sorting is a good idea.

**Comment by TheZoc** [comment]
@Melectrome Your comment creates the issue he attempted to avoid hahah :)

I'll merge this file on the next version.

**Comment by TheZoc** [comment]
Merged for RC5.
Maplist.txt can still be updated if you think there's a better order or if the starting map isn't ideal.
