### ISSUE TITLE
particle fixes

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#97]
Particles hard edges fixed as specified [here](https://steamcommunity.com/games/362890/announcements/detail/1715207569423590279)

[materials.zip](https://github.com/TheZoc/sourceforts-bug-tracker/files/2820119/materials.zip)

**Comment by Melectrome** [comment]
That's just plain cool. Pls apply!

**Comment by TheZoc** [comment]
Cool! I'll merge on next version :D

**Comment by TheZoc** [comment]
I just copied that to `materials/` for RC5!

Is there anything else needed for this fix? (No files were replaced!)

**Comment by arenaceous** [comment]
That should be it.
