### ISSUE TITLE
INFINITE SPRINT BUG: HELP WANTED!

### ISSUE THREAD

**Issue by Melectrome** [TheZoc/sourceforts-bug-tracker#99]
Okay, so me and PsychoAlex were fucking around on his server, and suddenly I noticed that I had infinite sprint - the sprint bar didn't appear and I could hold shift and run forever.
This means that the infinite sprint bug is kinda still a thing.
I have no clue how to reproduce this though.
This is why help is wanted.

If someone can effectively find a way to reproduce this bug, please respond

**Comment by Nick12506** [comment]
What map?

**Comment by Melectrome** [comment]
Doesn't matter, really.
Yesterday eurofags got together for a friday night pug, and it happened to me again on sf_sphinx.
I wish I was recording.

**Comment by TheZoc** [comment]
This seems to be a duplicate of #70 
Need to check server logs when this happens ASAP.

Do you think you can check this?

**Comment by Melectrome** [comment]
Yeah. I'll play around on my server and keep an eye on the logs.

**Comment by Melectrome** [comment]
Closing for #93

**Comment by TheZoc** [comment]
This wasn't supposed to be closed. Still, fixed in RC7 (Finally! 😁 )
